version: '3.7'

services:

  sample:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3010:3000
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=30000
      - FAST_REFRESH=false